### ISSUE TITLE
Unmapping all names on an enum and saving causes mapping to be lost

### ISSUE THREAD

**Issue by asiekierka** [FabricMC/Enigma#110]

**Comment by gegy1000** [comment]
Would this not be expected? There'd be nothing in the mapping file after. Probably misinterpreting the issue.

**Comment by asiekierka** [comment]
Enums can also have fields and methods. Try taking TextFormat, say, and unmapping all of the enum instances - but keeping the fields and methods.

**Comment by gegy1000** [comment]
Investigated this a bit, seems this is reproducible by unmapping any single member on a class without changing another -- the class mapping will be deleted. The current approach to saving is quite flawed, I'm going to look into using a slightly different system.
