### ISSUE TITLE
Enum constant names should always match their bytecode names

### ISSUE THREAD

**Issue by Runemoro** [FabricMC/Enigma#120]
Obfuscated enum constant names should be unmappable so that they always match the (synthetic) name parameter passed to the constructor. Otherwise, things `valueOf` won't work properly.

Additionally, some enum parameters aren't auto-mapped by Enigma and have been mapped to names that don't match the bytecode name (for example `NetworkState`). Here's the bytecode of the class showing that the network states are named `HANDSHAKING` (rather than `HANDSHAKE`), `PLAY` (rather than `GAME`), `STATUS` (rather than `QUERY`), and `LOGIN`: https://gist.github.com/Runemoro/84094f3e19e255ca5f2d450137cfd817

**Comment by asiekierka** [comment]
>Obfuscated enum constant names should be unmappable so that they always match the (synthetic) name parameter passed to the constructor. Otherwise, things valueOf won't work properly.

Not every game is sensible. We can assume this for Minecraft, but not necessarily others, IMO. Keep in mind Minecraft's ProGuard config is relatively lax - Starmade's is crazier.

**Comment by Runemoro** [comment]
I doubt any obfuscator would remap the actual name string of the enum, since that would break `valueOf` and `name`.

In any case, there's also the problem of some enums not being auto-mapped that needs to be fixed.

**Comment by liach** [comment]
This is implemented as part of #168.
