### ISSUE TITLE
net.minecraft.realms has obfuscated yarn names, yet are still somehow unobfuscated in source

### ISSUE THREAD

**Issue by Runemoro** [FabricMC/Enigma#121]
The mappings for the `net.minecraft.realms` package has mappings that look like these:

```
METHOD    net/minecraft/realms/RealmsClickableScrolledSelectionList    ()I    y0    method_1915    method_1915
```

which shows that their yarn name is the same as their intermediary (`method_1915`). Despite this, yarn still somehow shows the Mojang name `y0` in source:

```java
    public int y0() {
        return this.proxy.y0();
    }
```

Looking at names outside of the `net.minecraft.realms` package, their intermediary name matches their Mojang name:

```
METHOD    cwg    (I)Lcwg$a;    getEntry    getItem    getEntry
```

and they are correctly obfuscated to their yarn name!

```java
    protected E getItem(final int index) {
        return this.children().get(index);
    }
```

So there seem to be two bugs:
 - Unlike non-realms mappings, realms mappings are getting intermediaries that don't match the Mojang name
 - Realms mappings are being completely ignored

**Comment by modmuss50** [comment]
They should not have yarn.
They should also not get intermediary names, if they are this is an issue with stitch

**Comment by asiekierka** [comment]
* Yarn only incorporates Intermediary names at the build process.
* If a Yarn mapping is missing, the "intermediary" name will be copied to the "named" mapping as part of the merging process.
* It's impossible to perfectly detect obfuscated names from non-obfuscated ones. "y0" is an obfuscated name by the terms the intermediary system can currently detect.

Discussing with Player, the best solution going forward may well be to remap Realms just like we remap Minecraft.
