### ISSUE TITLE
For enum automappings, enigma prefers string parameters rather than the actual name

### ISSUE THREAD

**Issue by NeunEinser** [FabricMC/Enigma#124]
For example, in enum classes from `net.minecraft.client.options`, enigma auto maps the enum constants to a name derived from a string parameter in the enum's constructor rather than the actual name.
An example of this happening:
![grafik](https://user-images.githubusercontent.com/12124394/56993453-ca9f0480-6b9c-11e9-9d06-97734b49ba2e.png)
![grafik](https://user-images.githubusercontent.com/12124394/56993458-cecb2200-6b9c-11e9-96fe-f6de9f3bca37.png)
As you can see in the bytecode, the actual enum constants are `OFF`, `CROSSHAIR` and `HOTBAR`.

As a sidenote, this can potentially mess up `valueOf` and `name`, as described in #120.

**Comment by Runemoro** [comment]
https://github.com/FabricMC/Enigma/issues/120
