### ISSUE TITLE
Enum automappings fail when enum constant declaration declares an anonymous class

### ISSUE THREAD

**Issue by NeunEinser** [FabricMC/Enigma#125]
Enum constants from `net.minecraft.enchantment.EnchantmentTarget` do not receive an auto mapping. Presumably, this is the case, because the enum has an abstract method that gets overwritten in each enum declaration.
Automapping should definitely be possible, as the bytecode of the main class contains all enum names.

**Comment by Runemoro** [comment]
https://github.com/FabricMC/Enigma/issues/120

**Comment by liach** [comment]
Also #168. The corresponding issue has been fixed in stitch.
