### ISSUE TITLE
Unable to map complex method args

### ISSUE THREAD

**Issue by maxpowa** [FabricMC/Enigma#16]
Trying to map `a3` in the screenshot below results in the first argument being renamed rather than `a3`. Unable to rename `a1` or `a2` directly, method is found in `none/p`.

<img width="894" alt="screen shot 2016-08-28 at 9 21 26 am" src="https://cloud.githubusercontent.com/assets/1764978/18035011/ebe20be4-6d00-11e6-8a25-db7fa563a972.png">

**Comment by Thog** [comment]
So this bug reappeared for some reasons... related to #7
