### ISSUE TITLE
Method Inheritance view should only show classes the method is actually overridden in, if possible

### ISSUE THREAD

**Issue by asiekierka** [FabricMC/Enigma#20]
Might not be with the current system. Not a huge deal.

**Comment by mezz** [comment]
This would really streamline method naming in classes like Item and Block. There are many  inherited implementations that are just the same as their parents, and those are purely noise when trying to determine what the method does.

**Comment by asiekierka** [comment]
https://github.com/FabricMC/Enigma/commit/924ab1cfe379d5744d5c864b3236934a037a21ae
