### ISSUE TITLE
Could not find :darcula:1.0.0

### ISSUE THREAD

**Issue by SamirMokiem** [FabricMC/Enigma#205]
My build failes with this message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find :darcula:1.0.0.
     Searched in the following locations:
       - https://raw.githubusercontent.com/bulenkov/Darcula/master/build/darcula.xml
     Required by:
         project :
```

Info:
MacOs 10.15.2

java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)
OS:           Mac OS X 10.15.2 x86_64

**Comment by Chocohead** [comment]
I think Gradle 6 has changed something in Ivy resolution which has broken the way Darcular is grabbed as a dependency. As a short term fix you could backdate Gradle (such as using the provided wrapper) or change the dependency to `com.bulenkov:darcula:2018.2` and add `JCenter` as a repository.

**Comment by liach** [comment]
Guess you need to call https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/repositories/IvyArtifactRepository.MetadataSources.html#artifact-- from https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/repositories/IvyArtifactRepository.html#metadataSources-org.gradle.api.Action-
Like change https://github.com/FabricMC/Enigma/blob/aaa79a0b5d675e341c085b8743a3493c32784b1b/build.gradle#L60-L63 to
```gradle

	ivy {
		name "darcula"
		artifactPattern "https://raw.githubusercontent.com/bulenkov/Darcula/master/build/[module].[ext]"
		metadataSources {
			artifact()
		}
	}
```
A similar problem had happened as well when I tried to grab stuff from forge maven before with gradle 6. Forge maven also lacks metadata.
