### ISSUE TITLE
Source export failed, stackoverflowerror

### ISSUE THREAD

**Issue by SamirMokiem** [FabricMC/Enigma#207]
#206 fixed #205 and i was able to use enigma. But now after trying to export the source i get an stackoverflow

Using: #206

Version: 1.15.2 (official) with client mapping (official)

Log: https://pastebin.com/raw/bhrbdSdh

**Comment by liach** [comment]
Procyon is known to fail on some classes like `LivingEntity` and some data provider classes. Try with `Decompiler` set to `CFR`.

**Comment by SamirMokiem** [comment]
That also gives an error: https://pastebin.com/raw/mxDwWL16
Running with 8gb ram

**Comment by MightyCoderX** [comment]
i have 4gb of ram and it doesn't work with the default decompiler, it throws StackOverflow

**Comment by MightyCoderX** [comment]
Also tried a pc with 16GB of ram with bot compilers, it still keeps crashing

**Comment by SamirMokiem** [comment]
Version 0.14.3.149 worked.
Also it was a lot faster when decompiling

**Comment by Runemoro** [comment]
The Procyon issue can't be fixed from Enigma. We should merge the commit I mentioned in [this comment](https://github.com/FabricMC/procyon/issues/8#issuecomment-527480081) to Fabric's fork of Procyon.

I'll make a PR soon fixing the CFR issues.
