### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by Thog** [FabricMC/Enigma#21]

**Comment by MichelArendt** [comment]
Is there any way to reduce memory usage other than doing code optimization, like maybe some java arguments? I'm feeding 14GB and still can't get through to finishing decompilation for the server.

Not sure how the decompilation works, but it seems to keep everything on the memory. Any way around this?

Thanks in advance!

**Comment by liach** [comment]
Hmm, maybe a heap dump is needed to examine what is using the memory

**Comment by ehoffman2** [comment]
I've had similar problem decompiling Minecraft client 1.17.1 along with Mojang/Microsoft's provided ProGuard deobfuscation mapping file.
With default Java params I got "out of memory", same with -xmx 4GB.  When this happens, you only get hint in the console.  The program just look like it's continuing to crunch, my 16 threads are at approx 80%, but the progress bar no longer advance.

I upped -xmx to 16G (-xms4096M -xmx16386M) and it went through really fast without error (I have 32G).

Once this happens, I can not stop the program, ctrl-c on console does nothing, and kill does not work (have to kill -9).

This is on Ubuntu 20.04, enigma-swing-1.4.1+local-all.jar

Regards,
Eric

**Comment by 2xsaiko** [comment]
Why do you want to decompile the client using Enigma? You can use the genSources task from Fabric Loom, it's less memory intensive because it does only decompilation instead of having Enigma's overhead of indexing the entire code, if you want to use it for reference while developing mods.

**Comment by liach** [comment]
> Why do you want to decompile the client using Enigma? You can use the genSources task from Fabric Loom, it's less memory intensive because it does only decompilation instead of having Enigma's overhead of indexing the entire code, if you want to use it for reference while developing mods.

It's a function exposed in enigma's menu.

**Comment by ehoffman2** [comment]
> Why do you want to decompile the client using Enigma? You can use the genSources task from Fabric Loom, it's less memory intensive because it does only decompilation instead of having Enigma's overhead of indexing the entire code, if you want to use it for reference while developing mods.

That tool would probably be better suited.  I just used the first tool I found from a Youtube video "how to decompile minecraft".  I'm kind of newbie here :-)

I traced Enigma and there doesn't seem to be any leak.  Just a very high usage of hash maps, certainly from the size of Minecraft.

This was with compiling on Java 16 btw.

Regards

**Comment by novastosha** [comment]
I'm giving Egnima 16GB of memory but it still thorws OutOfMemoryException

**Comment by NebelNidas** [comment]
Should be fixed as of https://github.com/FabricMC/Enigma/pull/448, I think this issue can be closed
