### ISSUE TITLE
Closing mappings doesn't remove javadocs from the current view

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/Enigma#210]
Possibly related to #190.

Example: (everything here was mapped before)
![](https://user-images.githubusercontent.com/6596629/78454846-4655db00-76a3-11ea-9d7b-04dd14f0aef2.png)

**Comment by liach** [comment]
Renaming an entry does not refresh the javadoc as well. This is because javadoc is inserted by abstract syntax tree than token replacement.

**Comment by liach** [comment]
Is this now fixed given that javadoc not updating when rename was made bug was fixed?

**Comment by Juuxel** [comment]
Doesn't seem so (testing with 0.22.0 since that's what Yarn uses). Here's how `DrawableHelper` looks like after closing the mappings:

![](https://user-images.githubusercontent.com/6596629/105458540-75205a80-5c91-11eb-83ac-4e5c90ca08e0.png)

**Comment by liach** [comment]
Great. I think it just involves another call to [`Source.addJavadocs`](https://github.com/FabricMC/Enigma/blob/76ce6e5c795d9ab5f5f7c7dd308715f8a16124f3/enigma/src/main/java/cuchaz/enigma/source/Source.java#L8) when the mappings are closed.
