### ISSUE TITLE
Cannot rename class not in a package

### ISSUE THREAD

**Issue by minexew** [FabricMC/Enigma#215]
Trying to rename a class that is not in any package, Enigma complains that "Class must be in a package". Why? JARs like this exist in the wild.

**Comment by liach** [comment]
Yes, this is a weird hardcoded behavior. You must give the class a `none` package to put it in the default package, like `Main` class should be renamed to `none/Main`

**Comment by Runemoro** [comment]
Yes, this should be fixed. Moving classes to a package might not even be possible if the main class (unobfuscated name) is in the default package and it calls methods from other classes.
