### ISSUE TITLE
Enigma stopped exposing critical dependencies

### ISSUE THREAD

**Issue by liach** [FabricMC/Enigma#224]
After commit aad12650ea7394e315ebe170ceebb345c739577d, the pom received a big negative change, breaking enigma usage in yarn (because all the libraries are no longer exposed to yarn gradle buildscript)

https://maven.fabricmc.net/cuchaz/enigma/0.15.1%2Bbuild.159/enigma-0.15.1%2Bbuild.159.pom
https://maven.fabricmc.net/cuchaz/enigma/0.15.1%2Bbuild.163/enigma-0.15.1%2Bbuild.163.pom

Diff:
https://gist.github.com/ca0db6c0c2de60ed3e97407204247c75

Also compare::
https://maven.fabricmc.net/cuchaz/enigma/0.15.1%2Bbuild.159/
https://maven.fabricmc.net/cuchaz/enigma/0.15.1%2Bbuild.163/

the `all` jar has been removed. This seriously affects the usability of enigma, and should be fixed as soon as possible. (It is probably just a `assemble.dependsOn shadowJar` statement in `build.gradle`)

**Comment by asiekierka** [comment]
Ideally, it would be Yarn grabbing the Enigma deps and building a classpath - to save hard drive space and bandwidth.

**Comment by liach** [comment]
Well there is a reason maven exists (so you can grab all dependencies recursively). Don't think it is proper to simply remove dependencies from your pom as if you don't need them.
