### ISSUE TITLE
Obsfucated classes stay in the obfuscated panel when named

### ISSUE THREAD

**Issue by Yanis48** [FabricMC/Enigma#228]
Happens since a long time, there just wasn't an issue for it yet.

When you name an obsfucated class, it moves in the deobsfucated panel, but doesn't move out the obsfucated panel. Restarting Enigma fixes the issue.

May come from `Gui.moveClassTree()`.

**Comment by liach** [comment]
In fact I like this bug because it allows me to rename classes more easily when I come up with better ideas after browsing associated classes

**Comment by Yanis48** [comment]
That's why tabs would be so useful

**Comment by immibis** [comment]
@liach Couldn't you look up the name you gave the class?

**Comment by Earthcomputer** [comment]
Maybe he could if the search menu wasn't broken :D

**Comment by liach** [comment]
Or if we can sort classes by obf names that would be fine too
