### ISSUE TITLE
Fix entry mapping

### ISSUE THREAD

**Issue by liach** [FabricMC/Enigma#237]
For long, Entry mapping can be `null`, indicating an absence of mapping. Entry mapping always require a mapped name to be present; however, besides mapped names, it carries other information, mainly access modifier change and javadoc.

As a result, you cannot have standalone javadoc information without mapping. This has become problematic, and a solution is to revamp all entry tree usages from nullable entry mapping to non-null no-op entry mapping instead, and we can revamp entry mapping itself to carry javadoc information without a rename.

**Comment by Runemoro** [comment]
I think https://github.com/FabricMC/Enigma/pull/188 fixes this?

**Comment by modmuss50** [comment]
Looks like it does.

It will need testing.

**Comment by liach** [comment]
That pr misses a lot of places, as in existing enigma code there is widespread assumption that target name cannot be `null` in an entry mapping, and that pr apparently takes care of none of that. Also that pr allows an entry mapping to be effectively same as `null` by having null javadoc + null target name, yet that pr does not handle that at all (still using `null` checks without checking members)

**Comment by YanisBft** [comment]
Fixed by #364 it seems
