### ISSUE TITLE
i saw people have 3 jars in libs and i have 1 fix this so that make 3 jars

### ISSUE THREAD

**Issue by axcsds** [FabricMC/Enigma#241]
me:

![image](https://user-images.githubusercontent.com/48110639/81896918-26a3b380-957b-11ea-9062-dd9bf7a043ed.png)

and other people:

![image](https://user-images.githubusercontent.com/48110639/81896953-33c0a280-957b-11ea-8bff-20b6b608b09d.png)

**Comment by Juuxel** [comment]
You need to use `gradlew build` instead of `gradlew jar`.

**Comment by axcsds** [comment]
i use gradlew build but same thing

**Comment by axcsds** [comment]
this picture https://user-images.githubusercontent.com/48110639/81896918-26a3b380-957b-11ea-9062-dd9bf7a043ed.png

**Comment by axcsds** [comment]
me after using gradlew build

**Comment by axcsds** [comment]
help?

**Comment by liach** [comment]
You do like `gradle publishToMavenLocal`

**Comment by axcsds** [comment]
help?
pls?

**Comment by liach** [comment]
Hey please shut up, I've given you instructions and you just keep spamming

**Comment by axcsds** [comment]
> You do like `gradle publishToMavenLocal`

gradle publishToMavenLocal is not a command

**Comment by liach** [comment]
`gradlew publishToMavenLocal` then lol

**Comment by liach** [comment]
@axcsds where have you gone? if you are done close this issue
