### ISSUE TITLE
Fix broken renaming in package list

### ISSUE THREAD

**Issue by copygirl** [FabricMC/Enigma#25]
Renaming classes appears to be possible, but after reloading, doesn't do anything.

**Comment by copygirl** [comment]
The same seems to be true for renaming classes, causing them to be moved to a different package, until you save.

**Comment by copygirl** [comment]
Alright, here a couple of issues I noticed:
- Renaming sometimes causes me to be unable to check out classes afterwards until reloading mappings.
- It's possible to rename a type into a different package using `/`, but it's not updated / moved there.
- Incorrect order after renaming.
- Various errors after renaming.
- Enigma hangs when renaming and doesn't seem to recover.

**Comment by Thog** [comment]
@copygirl If you are able to find a way reproduce some of them, I will love to fix them. Anyway, the incorrect order issue will be probably hard to fix, I'm doing thing that in theory isn't allowed to do, I will do my best to fix it.

**Comment by YanisBft** [comment]
Several PRs fixed renaming issues. Please reopen an issue if broken cases still remain
