### ISSUE TITLE
Enigma completely freezes after shortcut combo

### ISSUE THREAD

**Issue by Kroppeb** [FabricMC/Enigma#252]
* Select a renamable element
* Press `ctrl + e`
* Press `ctrl + z`
* Select the element again
* Press `ctrl + r`
* Rename the item
* Press enter

This freezes the enigma, which can now only be closed using the task manager, causing any unsaved mappings to be lost.

Environment:
JVM: 14 (Eclipse OpenJ9 openj9-0.19.0)
OS: Windows 10 10.0 amd64

**Comment by 2xsaiko** [comment]
Can't reproduce in fba687f, does it still happen for you?

**Comment by 2xsaiko** [comment]
Ctrl+e removes the entire line which I'd definitely classify as a bug, though since the editor is not supposed to be editable.

**Comment by Kroppeb** [comment]
It seems it has been fixed =)
