### ISSUE TITLE
java.lang.StackOverFlowError

### ISSUE THREAD

**Issue by balaramsudip** [FabricMC/Enigma#256]
Enigma replaces my files with Java.lang.StackOverflowError, and 100 other crash lines talking about enigma crashing.

**Comment by balaramsudip** [comment]
OH, I should clarify, I meant the files that were supposed to be from the "export source" option.

**Comment by 2xsaiko** [comment]
Could you attach the stack trace?

**Comment by Yoreni** [comment]
looks like i get the same error

[enigma_crash.log](https://github.com/FabricMC/Enigma/files/4813466/enigma_crash.log)

**Comment by 2xsaiko** [comment]
If it is that crash, closing in favor of #279 since that has more information.
