### ISSUE TITLE
Project formatting

### ISSUE THREAD

**Issue by 2xsaiko** [FabricMC/Enigma#269]
The code should either be formatted with tabs or with spaces. Right now there's a mix of both.

**Comment by modmuss50** [comment]
I would suggest applying the same if not similar checksyle that is used across the other fabric projects.

**Comment by 2xsaiko** [comment]
Eeeeh, even having to fix IDEA indenting the file wrongly in some of the classes you edit is way less of a pain than having to deal with checkstyle imo. I'd really rather not.

**Comment by modmuss50** [comment]
The gradle task only validates it. There is an idea plugint that will validate it as you type.

As for a formatter there is an idea config somewhere that will do most if not all of it for you. I usually just do it by hand tho.

Failing that adding a editor config file to specify tabs and passing an auto formatter over it would be a good improvement

**Comment by NebelNidas** [comment]
Fixed as of 9c736848fb7aa82d295b3aa2946e6cd132ee998f
