### ISSUE TITLE
Mapping convertion doesn't work

### ISSUE THREAD

**Issue by MrIvanPlays** [FabricMC/Enigma#274]
I tried converting proguard mappings to enigma ones, and it didn't work. I got blank file

**Comment by KennyTV** [comment]
Works fine for me `java -cp $enigma cuchaz.enigma.command.Main convert-mappings proguard client.txt enigma mapping`

**Comment by MrIvanPlays** [comment]
> Works fine for me `java -cp $enigma cuchaz.enigma.command.Main convert-mappings proguard client.txt enigma mapping`

I found whats wrong... I was doing enigma_file . thanks
