### ISSUE TITLE
StackOverFlow during decompile

### ISSUE THREAD

**Issue by KennyTV** [FabricMC/Enigma#279]
Decompiling the Vanilla client/server with both cfr and procyon is bork. I could at least make it finish (only with procyon) and skip erroneous classes by putting a try catch over the decompile call in the loop.
Not sure if you can actually do anything about that, but then at least a try catch clause would be appreciated

Errors are: https://paste.gg/p/anonymous/9ad081a2dc2f484faf87f7865e6aad25

Edit: Hacked a full decompile together by using procyon and falling back to cfr it pro fails 👀

Affected classes are these with procyon, I haven't looked for any patterns in their contents tho
```
net/minecraft/world/level/levelgen/placement/NoiseHeightmap32Decorator
net/minecraft/gametest/framework/GameTestRunner
net/minecraft/util/datafix/fixes/SwimStatsRenameFix
net/minecraft/world/level/levelgen/placement/CountChanceHeightmapDoubleDecorator
net/minecraft/util/datafix/fixes/VillagerRebuildLevelAndXpFix
net/minecraft/util/datafix/fixes/LeavesFix
net/minecraft/world/level/levelgen/placement/NoiseHeightmapDoubleDecorator
net/minecraft/world/level/levelgen/placement/CountHeighmapDoubleDecorator
net/minecraft/world/entity/LivingEntity
net/minecraft/world/level/levelgen/placement/CountHeightmap32Decorator
net/minecraft/util/datafix/fixes/ItemStackUUIDFix
net/minecraft/server/level/ChunkMap
```

**Comment by Yoreni** [comment]
i got this too plz fix

**Comment by 2xsaiko** [comment]
Also mentioned in #126

**Comment by gcurtiss** [comment]
Can confirm broken. Can't decompile latest 1.16 jar.

**Comment by LaserSlimeHD** [comment]
Im getting a different stockoverflow when trying to export 1.16.1 server as a zip, but i can just export it as jar and then decompile it.

**Comment by Karol739** [comment]
I confirm. I can't decompile **anything**. Please fix it! This bug appear in older versions too.

**Comment by liach** [comment]
Shall you export code for yarn, you can use `gradlew mapNamedJar` and decompile that jar for now.

**Comment by balaramsudip** [comment]
I am switching to yarn mappings for some time, this decompiling is still broken! And this time, it crashes while decompiling.

**Comment by 2xsaiko** [comment]
> I am switching to yarn mappings for some time, this decompiling is still broken! And this time, it crashes while decompiling.

If it's a different crash, please open another issue.

**Comment by 2xsaiko** [comment]
The CFR error is better detailed in #283, and they're unrelated bugs as far as I can see so I'll be removing the CFR tag from this issue.

**Comment by KennyTV** [comment]
Pretty sure erroring classes don't completely kill the decompile process anymore, so 🐱‍🏍
