### ISSUE TITLE
[Bug] Text box that allows you to rename stuff is broken

### ISSUE THREAD

**Issue by BoogieMonster1O1** [FabricMC/Enigma#280]
I noticed that the text box which allows you to rename stuff in a class has its font size and height a wee bit high but it's kinda irritating.

Java version: 8u252
Operating System: Mac OS 10.15.4
Allotted memory: 64 MB

![Screen Shot 2020-06-20 at 1 28 55 PM](https://user-images.githubusercontent.com/62552372/85196788-317c0180-b2fa-11ea-8e28-71368528f9be.png)
That's supposed to have underscores in the blank gaps, but they aren't visible

**Comment by 2xsaiko** [comment]
You're using an out of date version of Enigma. This shouldn't happen in the current version, can you test it?

This is what it looks like for me:
![image](https://user-images.githubusercontent.com/3987560/85200004-2f16a900-b2f4-11ea-839d-d5afe5a479a4.png)

**Comment by haykam821** [comment]
I can't reproduce on Mac as well:
![Mac Enigma](https://user-images.githubusercontent.com/24855774/85200156-fdd1b500-b2c2-11ea-92ca-51997cf915d6.png)
