### ISSUE TITLE
Search dialog sometimes freezes up when updating search results

### ISSUE THREAD

**Issue by 2xsaiko** [FabricMC/Enigma#282]
Seems to be somewhat reliably reproducible by opening up a class using the search dialog, then opening the search dialog again, entering "C" and pressing backspace. Not sure why it doesn't always occur.

From what I can tell, it locks up because every time the async callback is called with one of the search results, it submits a task to be executed on the AWT thread which updates the results list, and under certain circumstances this task takes a long time to complete (according to the profiler, it's stuck a lot in `JLabel.setText`, and `revalidate`, `repaint` and `firePropertyChange` make up the biggest percentage of what gets called from setText)

Profiler output from IntelliJ: [13904_GUI_2020-06-24-141058.collapsed](https://github.com/FabricMC/Enigma/files/4826908/13904_GUI_2020-06-24-141058.collapsed.txt)

**Comment by liach** [comment]
This thing almost always happen when you type "client", presumably due to this word occuring so often. Maybe we can limit the search to give first few relevant results or so.

**Comment by liach** [comment]
No longer a problem in 1.3.2. Need to bump enigma in yarn later.
