### ISSUE TITLE
import lots of mappings

### ISSUE THREAD

**Issue by lihuoran-oier** [FabricMC/Enigma#285]
I tried to use Enigma and [yarn](https://github.com/FabricMC/yarn) to deobcause the Minecraft source code. 
But the mappings in yarn is too much.it isnt in the one file.but they are in the same dict or in its sub-dicts.
Can you add a function to import lots of `.mapping`s or `.txt`s in the same dirc or in its sub-dirc in one try?

**Comment by 2xsaiko** [comment]
Use File -> Open Mappings... -> Enigma Directory to open it.

Also, for Yarn specifically, you can just run `./gradlew yarn` to open Enigma and have it automatically open the jar and mappings.

**Comment by lihuoran-oier** [comment]
I didn't find `Enigma Directory`. In File->Open Mappings ,I can't choice Directory.Can you help me?(Or is it this function is new in v0.11(i'm using v0.10)?)
And because i'm Chinese,so i need VPN to connect `raw.githubusercontent.com`,so i can't use `gradlew yarn`.=(

**Comment by 2xsaiko** [comment]
Are you saying this doesn't work for you?

![image](https://user-images.githubusercontent.com/3987560/86135317-ee384480-baea-11ea-8e72-23d89ba8f16c.png)

**Comment by lihuoran-oier** [comment]
hmmmmm.......your enigma looks different with me.where did you download it?i download it at [here](www.cuchazinteractive.com/enigma).
![it looks like this](https://i.loli.net/2020/07/01/YUgiwOaExpoFPt3.png)

**Comment by 2xsaiko** [comment]
Yeah no wonder, that's an absolutely ancient version. Here's the current builds, download the latest jar that has the -all suffix. https://maven.fabricmc.net/cuchaz/enigma-swing/

**Comment by lihuoran-oier** [comment]
> Yeah no wonder, that's an absolutely ancient version. Here's the current builds, download the latest jar that has the -all suffix. https://maven.fabricmc.net/cuchaz/enigma-swing/

Thanks very much.I found it.
