### ISSUE TITLE
Methods overridden from a superclass do not show mapped names

### ISSUE THREAD

**Issue by BoogieMonster1O1** [FabricMC/Enigma#286]
Overridden methods do not show mapped names in the subclasses.
The same methods in the superclass show mapped names.

In the subclass, the method is actually mapped, but it does not show as such unless it is selected.
![Screen Shot 2020-06-26 at 9 27 11 PM](https://user-images.githubusercontent.com/62552372/85876916-0874d880-b7f4-11ea-9f41-e5a980b51328.png)

That same method in the superclass shows that it is indeed mapped.
![Screen Shot 2020-06-26 at 9 33 31 PM](https://user-images.githubusercontent.com/62552372/85877393-b7191900-b7f4-11ea-8f95-7b9f49bdce70.png)

It also happens with method parameters.

Tested versions: 0.19+build.197, 0.19+build.198
Allotted memory: 64 MB
Java version: 11.0.7

**Comment by 2xsaiko** [comment]
This will be fixed with #284
