### ISSUE TITLE
java.lang.StackOverFlowException when export source

### ISSUE THREAD

**Issue by lihuoran-oier** [FabricMC/Enigma#290]
I'm going to open issue again!(
I was using `gradlew mapNamedJar` in yarn to make a deobcaused Jar for minecraft with VPN.
but when i open it with enigma and try to export source code,i got a java.lang.StackOverFlowException.
this is the log.
[enigma_crash.log](https://github.com/FabricMC/Enigma/files/4877303/enigma_crash.log)
i thought maybe my computer is too old to decomplie the code with enough memory and i found a friend to do it again.
He used `java -jar -Xmx10G enigma.jar` but he also get a StackOverflowException.
is this a bug of enigma?

**Comment by lihuoran-oier** [comment]
is it the same bug with #279 ?

**Comment by 2xsaiko** [comment]
It is, yeah.
