### ISSUE TITLE
"java.lang.OutOfMemoryError" Issues.

### ISSUE THREAD

**Issue by ThePillager** [FabricMC/Enigma#296]
Hi ! 
This Issue happened when i was exporting the source ,
Sorry i don't Have the crash log !

RAM:4GB

**Comment by 2xsaiko** [comment]
Decompilation is pretty memory intensive. I doubt there's a lot that can be done about this except giving it more memory. Especially if 4GB is your all the RAM your computer has, because that means Enigma would get like half of that at best.

**Comment by Guiorgy** [comment]
FYI, tried trice (1.16.5 client) with usage jumping to about 18GB (out of 32). In the end I used `-Xms20G -Xmx22G` as java arguments, memory usage jumped to 23GB (that's including everything else running on the system) and process ended soon successfully, so...
> Decompilation is **_pretty_** memory intensive

is an understatement :P
