### ISSUE TITLE
Allow changing package names by right-clicking them in the deobfuscated classes list

### ISSUE THREAD

**Issue by haykam821** [FabricMC/Enigma#298]
Right now, there doesn't seem to be a quick way to change an entire package's name, like I did in FabricMC/yarn#1584. To fix this gap in functionality, a context menu should be added to the sidebar's deobfuscated classes list that allows one to rename the entire package.

**Comment by 2xsaiko** [comment]
There is, select an entry in the tree and press f2 to start renaming. Pretty sure it's kinda janky though.
