### ISSUE TITLE
Fix type renaming input being cut off on Linux?

### ISSUE THREAD

**Issue by copygirl** [FabricMC/Enigma#30]
[Picture of bug.](http://i.imgur.com/KKuMiqs.png)

**Comment by Thog** [comment]
It's the look n feel that use Java for Gnome that is wrong, with the default look and feel it's good. Anyway, it stills a bug, I will try to fix it when I will have resetup my archlinux.

**Comment by modmuss50** [comment]
It might work without the L&F, might be able to add a way to use the old that existed before OML's fork.

**Comment by Thog** [comment]
Yeah, maybe a command line argument?

**Comment by NebelNidas** [comment]
Since this is a LAF problem, and Enigma now offers the ability to chose between multiple different options, I consider the issue fixed.
