### ISSUE TITLE
Calling an inferred parameter name deobfuscated resets it to its obfuscated name

### ISSUE THREAD

**Issue by sschr15** [FabricMC/Enigma#314]
Enigma can sometimes guess a parameter name. When you attempt to mark it as deobfuscated, the old version of Enigma would correctly save it as the inferred name. However, this fork of Enigma will reset the name to the obfuscated version regardless of if it inferred the name.

Old Enigma example:
![Old Enigma marking an inferred entity name as deobfuscated](https://user-images.githubusercontent.com/15277819/94278595-a15ce200-ff10-11ea-9f78-6d40d3c0ee06.gif)

New Enigma example:
![New Enigma "deobfuscating" entity by resetting it to b](https://user-images.githubusercontent.com/15277819/94278953-1203fe80-ff11-11ea-9e58-81c9f00dd8cf.gif)

**Comment by 2xsaiko** [comment]
Fixed in https://github.com/2xsaiko/Enigma/commit/aaae971304f38486bd7928c47710d4b13052c97a, should be merged into master eventually
