### ISSUE TITLE
Java cant find 'cuchaz.enigma.command.CommandMain' on cli

### ISSUE THREAD

**Issue by Fahoom** [FabricMC/Enigma#335]
As said in the title, while trying to use Enigma with the enigma-cli-0.22.0-all.jar, i get the following error

```
C:\Programming\spectral\mappings\download>java -cp enigma.jar cuchaz.enigma.command.CommandMain
Error: Could not find or load main class cuchaz.enigma.command.CommandMain
Caused by: java.lang.ClassNotFoundException: cuchaz.enigma.command.CommandMain
```

I am using Java 11, on Windows, and it occurs while attempting to use any command

Thanks in advance

**Comment by 2xsaiko** [comment]
You need enigma-cli I believe, not enigma (which is at this point just a library, not an executable)

**Comment by Fahoom** [comment]
i was using enigma-cli, just renamed to enigma.jar. Sorry about that

**Comment by 2xsaiko** [comment]
I don't know where you got yours from, but I just tested with the latest (0.22.0) from here <https://maven.fabricmc.net/cuchaz/enigma-cli/> (you need the jar that has -all at the end) and it works even with just "java -jar enigma-cli-0.22.0-all.jar".

**Comment by Fahoom** [comment]
It's alright I managed to figure it out, the help on the CLI version says to use 'cuchaz.enigma.Command.CommandMain' instead of 'cuchaz.enigma.Command.Main', might be worth fixing that

Thanks anyways
