### ISSUE TITLE
cfr doesn't show javadoc for enums

### ISSUE THREAD

**Issue by liach** [FabricMC/Enigma#345]
Since fabric cfr doesn't have issues enabled, leaving it here so I can remind myself. Tested with SlotActionType.

**Comment by liach** [comment]
In additon, seems cfr doesn't properly tokenize super class' field references. Need to check on that as well when I come back.

**Comment by liach** [comment]
Additionally, for anno classes cfr doesn't yet show docs. This is becoming a problem as since 21w13a Minecraft is shipping annotations.

**Comment by YanisBft** [comment]
When opening an enum with CFR, this appears:
![image](https://user-images.githubusercontent.com/16228338/115152983-ea72b000-a073-11eb-8036-a0f0075a2f00.png)

I guess javadocs not showing could be related to this

**Comment by liach** [comment]
Yes, this is another side effect of non-class/interface class writers not calling appropriate dumper methods for javadoc/dumper methods writing those class names aren't catched by enigma's custom dumper.

**Comment by liach** [comment]
For yanis's problem, it looks like we need to make this
https://github.com/FabricMC/cfr/blob/ab2cc7dabb9248d6e9eef3818f5b323421b32cfd/src/org/benf/cfr/reader/entities/classfilehelpers/ClassFileDumperEnum.java#L37
more specifically, the `.dump(c.getThisClassConstpoolEntry().getTypeInstance())` call to dump the type instance as a type declaration than a simple reference. Changing to `.dump(c.getThisClassConstpoolEntry().getTypeInstance(), true)` should work.

**Comment by YanisBft** [comment]
Now fixed as cfr was bumped
