### ISSUE TITLE
Unable to convert mappings due to java.nio.file.ProviderNotFoundException error

### ISSUE THREAD

**Issue by sc39IsADev** [FabricMC/Enigma#347]
I'm currently trying to convert an enigma mapping file to a proguard mapping file. When I try to convert it, I get this error:
`java.nio.file.ProviderNotFoundException: Provider not found`
Here's the command I used:
`java -cp "enigma-0.23.0.jar:enigma-cli-0.23.0.jar" cuchaz.enigma.command.Main convert-mappings enigma in.txt proguard out.txt`

**Comment by sc39IsADev** [comment]
Just tried the `-all` CLI jar to see if that fixed it, and it still had that error.

**Comment by Juuxel** [comment]
Proguard mappings are read-only in Enigma, so you can't convert a file from another format to that format.

**Comment by sc39IsADev** [comment]
Then how do I solve the problem of converting an Enigma mapping into a proguard mapping?

**Comment by sc39IsADev** [comment]
Never mind. I just ended up using the Enigma deobfuscator.
