### ISSUE TITLE
Copy Identifier info on click

### ISSUE THREAD

**Issue by Toshimichi0915** [FabricMC/Enigma#349]
Mod Development using Mixin will be much easier if identifier info can be copied on click, especially when the method signature is complex.
![image](https://user-images.githubusercontent.com/26406334/108637164-ca3bd000-74cc-11eb-9761-1e42c968f341.png)

**Comment by Prospector** [comment]
you're using Enigma for mod development?

**Comment by Toshimichi0915** [comment]
yes

**Comment by Toshimichi0915** [comment]
I thought everyone was using Enigma for mod development using Mixin.
What do people use if not Enigma?

**Comment by modmuss50** [comment]
There is a minecraft development plugin for intelij that adds this functionality along with auto complete.

**Comment by Toshimichi0915** [comment]
oh... lol
The plugin is pretty useful
Thanks for the info

**Comment by Toshimichi0915** [comment]
Do you think I should close this issue and the PR?
I think this feature is still useful to some people.

**Comment by liach** [comment]
fyi yarn javadoc has mixin info like https://maven.fabricmc.net/docs/yarn-21w07a+build.10/net/minecraft/structure/OceanMonumentGenerator.PieceFactory.html#generate(net.minecraft.util.math.Direction,net.minecraft.structure.OceanMonumentGenerator.PieceSetting,java.util.Random)
