### ISSUE TITLE
Progress bars are dummy THICC

### ISSUE THREAD

**Issue by Sollace** [FabricMC/Enigma#366]
![](https://cdn.discordapp.com/attachments/521545796882006027/826373309285269524/unknown.png)

I'm trying to work on yarn but Enigma is dummy thicc and the clap of it's progress bars keeps alerting the guards.

**Comment by 2xsaiko** [comment]
For some reason, doing it like that is the only way I could get it to consistently display, otherwise it would be cut off at the bottom of the window the very first time the dialog is opened. I'm at a loss as to what's happening there, probably yet another instance of Swing being janky as all hell. If anyone has a fix it would be very welcome.

**Comment by AyHa1810** [comment]
is this just me, or is it lookin....kindaa........**THICC!**

**Comment by DevCharly** [comment]
Removing this line:
https://github.com/FabricMC/Enigma/blob/b3136e382d6d86d95578c150cf2fbae1656427aa/enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/ProgressDialog.java#L52

And padding from this line:
https://github.com/FabricMC/Enigma/blob/b3136e382d6d86d95578c150cf2fbae1656427aa/enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/ProgressDialog.java#L58

should fix the progress bar height.

Better use gridbag insets to add some empty space around the progress bar.

**Comment by 2xsaiko** [comment]
@DevCharly I tried that already, it just made the progress bar be very small the first time this dialog opens (or not showing at all). I'm guessing this is a very weird race condition or something. Here's what happens with those changes (and without 41f009e, I didn't see your comment before)

First time the dialog opens:
![image](https://user-images.githubusercontent.com/3987560/113719736-3b86b980-96ee-11eb-8d58-25391eacf979.png)

Everything afterwards:
![image](https://user-images.githubusercontent.com/3987560/113719801-4b9e9900-96ee-11eb-9a71-b6f0e49765c5.png)

That's what I originally wanted to fix by setting the size explicitly, and I think 41f009e fixes it for about 90% of Enigma runs for whatever reason (I was just throwing stuff at it to see if something improved it) but it's still not perfect. And it also makes it not be that large :P
