### ISSUE TITLE
When editing javadocs, clicking "Ok" takes you to the first use of the method rather than its definition

### ISSUE THREAD

**Issue by Sollace** [FabricMC/Enigma#367]
As the title says.

1. Right-click on method definition
2. Edit javadoc
3. Type anything
4. Click okay
5. Enigma jumps to a random spot in the class where your selected method is being used (usually the first)

**Comment by 2xsaiko** [comment]
Also occurs only with CFR. As you already said, looks like it's the same/a similar bug as #368.

**Comment by liach** [comment]
This bug is because the entry references in cfr ain't properly generated due to how cfr prints methods. Same as #368.

**Comment by liach** [comment]
I think this definition bug has been fixed. It's only the reference one that I am currently fixing.
