### ISSUE TITLE
Clicking items in the call graph does not take you to the usage

### ISSUE THREAD

**Issue by Sollace** [FabricMC/Enigma#368]
Related to #367, clicking items in the call graph doesn't take you to the actual line. It opens the containing class, but leaves you at the very top, and if the class is already open nothing happens at all.
![image](https://user-images.githubusercontent.com/6429283/112968987-1f62a580-914d-11eb-9c71-0253d6d5a020.png)

**Comment by Sollace** [comment]
This is using CFR, ofc

**Comment by 2xsaiko** [comment]
This works fine with Procyon so I assume it's a bug in the implementation of this feature for CFR.

@Runemoro any ideas? The SourceIndex.referenceToTokens map has an empty list for the reference I've tested it with (retrieved through the flatMap call in GuiController.getTokensForReference)
