### ISSUE TITLE
Converter - Rework the method mapper

### ISSUE THREAD

**Issue by Thog** [FabricMC/Enigma#37]
Because I have a bad memory
<asie> Thog: For the method remapper
<asie> if a method signature is _not_ unique in the class _or_ provided by an interface
<asie> it should compare lists of fields accessed by a given method

**Comment by modmuss50** [comment]
Ok, here is my plan for this: 

https://docs.google.com/document/d/1dFMCkm6EFmqjrsyM1-VvdBBJLrKrXf_uxqneSdMdPeU/edit?usp=sharing

Let me know if its all wrong and wont work.

**Comment by modmuss50** [comment]
https://github.com/sfPlayer1/Matcher solves the issue.
