### ISSUE TITLE
Scrollbars are missing adjustment arrows

### ISSUE THREAD

**Issue by Sollace** [FabricMC/Enigma#370]
This is more just a minor usability tweak rather than an actual bug.

The adjustment arrows are those little up/down/left/right arrows on the ends of the scrollbars that let you move them by small increments.
![image](https://user-images.githubusercontent.com/6429283/112970331-5dac9480-914e-11eb-8a0a-eeef010ec9dd.png)

They are also unusually narrow when compared to other standard programs.

**Comment by 2xsaiko** [comment]
Pretty sure that's dependent on the Look and Feel. They're there for me when using Metal. There's probably a way to get them to always show up but I'm not sure how involved it would be.

**Comment by DevCharly** [comment]
If FlatLaf is used for the left screenshot, then that's easy to enable:
https://www.formdev.com/flatlaf/customizing/#scrollbar

But nowadays with every computer having a scroll wheel or a touchpad, the scroll arrows are rarely used.
That's the reason why they are hidden by default in FlatLaf. 😉

**Comment by 2xsaiko** [comment]
> If FlatLaf is used for the left screenshot, then that's easy to enable:
> https://www.formdev.com/flatlaf/customizing/#scrollbar

Ah, thanks! I already saw FlatLaf has a lot of customization options when fixing #365, that's very nice.

> But nowadays with every computer having a scroll wheel or a touchpad, the scroll arrows are rarely used.
> That's the reason why they are hidden by default in FlatLaf. :wink:

That's understandable, I at least very rarely use them. However, I think them being there doesn't hurt either for people who want to use them so I might as well turn that option on.
