### ISSUE TITLE
Mapping something WARNING makes the color on Enigma red

### ISSUE THREAD

**Issue by apple502j** [FabricMC/Enigma#374]
This can be seen on PolarBearEntity.

**Comment by 2xsaiko** [comment]
Same goes for ERROR but then it also becomes bold and italic. :thinking:

**Comment by Juuxel** [comment]
https://github.com/Sciss/SyntaxPane/blob/85fdde1ae8ce4329345e75b4d3bc8f2d38eb0b68/src/main/jflex/de/sciss/syntaxpane/lexers/java.flex#L178-L179

It's a SyntaxPane thing.
