### ISSUE TITLE
Failing to launch on my machine (Windows 10, AdoptOpenJDK 11)

### ISSUE THREAD

**Issue by chexo3** [FabricMC/Enigma#382]
Even when using a binary I compiled myself.

```
C:\Users\redacted\Desktop>java -jar enigma-swing-0.27.1.jar
Error: Unable to initialize main class cuchaz.enigma.gui.Main
Caused by: java.lang.NoClassDefFoundError: joptsimple.OptionSpec

C:\Users\redacted\Desktop>java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20210120_899 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)

C:\Users\redacted\Desktop>
```

**Comment by chexo3** [comment]
`gradlew build` worked, but the produced binary had the same issue

**Comment by chexo3** [comment]
Nevermind, I'm dumb. I'm assuming the `-all` jar file is the one with the dependencies shaded in. Would appreciate an explanation of how someone runs a jar with dependencies that aren't shaded in though, for future reference.

**Comment by ByMartrixx** [comment]
If you want to run the normal jar, you still have to provide each dependency jar individually via classpath. So, if the jar depends on gson and guava (depends on other ones as well), you have to use `java -cp gson.jar;guava.jar -jar Enigma.jar`

**Comment by chexo3** [comment]
noted, thanks
