### ISSUE TITLE
Unable to name methods from inner classes.

### ISSUE THREAD

**Issue by mezz** [FabricMC/Enigma#40]
I was unable to rename methods in `BlockStateFactory$BlockState` that are defined in `IBlockInfoProxy`. It would just not apply. One example method is `isFullBoundsCube` `b ()Z`. The workaround was to go to the interface and name them there.

**Comment by Thog** [comment]
Related to #3

**Comment by gegy1000** [comment]
Seems to no longer be an issue as of #91
