### ISSUE TITLE
fabric maven builds: they require java 16 !

### ISSUE THREAD

**Issue by Lanchon** [FabricMC/Enigma#404]
when trying to run the prebuilts i get:

```
Error: LinkageError occurred while loading main class cuchaz.enigma.gui.Main
	java.lang.UnsupportedClassVersionError: cuchaz/enigma/gui/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0) [...]
```

60.0 is java 16. if this project supports java 8 onwards, would it not be better to build the releases using java 8 or otherwise the oldest java possible beyond 8?

thanks!

**Comment by Juuxel** [comment]
The newest versions of Enigma only support Java 16 and up (and they use J16 features in the code as well AFAIK, so it is the oldest possible version).

**Comment by Lanchon** [comment]
ok i thought i read somewhere it supported java 8+. guess i'm wrong then?

**Comment by Lanchon** [comment]
@Juuxel you are right v1.0.0 is the last release to support old JVMs. thanks!
