### ISSUE TITLE
Pressing "save" in the close confirmation dialog doesn't save changes

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/Enigma#407]
To reproduce:
- Open a jar and a mapping set in Enigma (eg. with `gradlew yarn`)
- Rename something
- Press the window's close button without saving beforehand
- When the confirmation dialog about unsaved changes appears, choose "Save"
- Your changes won't be saved.

**Comment by liach** [comment]
I think I might have encountered this before, that I clicked save and turns out the changes don't appear in git and the directory.

**Comment by YanisBft** [comment]
The issue comes from `GuiController.saveMappings()` where the actual saving is ran offthread, so the main thread exits the program before the saving is completed (see `Gui.close()`)
