### ISSUE TITLE
control+space hotkey should open search window even if the focus is not on file bar

### ISSUE THREAD

**Issue by liach** [FabricMC/Enigma#408]
Tested in 1.3.2.

**Comment by YanisBft** [comment]
It works the same as before, the hotkey works when your cursor is in the identifier or the editor panel, but not when you have something selected in the left or right panels

**Comment by liach** [comment]
Yeah I think this is my error indeed!

**Comment by 2xsaiko** [comment]
It's probably better if the hotkey works everywhere as opposed to only sometimes depending on what is focused, I think the current behavior is really unintuitive.

**Comment by liach** [comment]
Hmm, so what do I need to focus on to make the hotkey work, just curious

**Comment by 2xsaiko** [comment]
According to StackOverflow, calling registerKeyboardAction on the root pane of the main window with the condition parameter being JComponent.WHEN_IN_FOCUSED_WINDOW should work?

**Comment by liach** [comment]
Wait, @2xsaiko if the hotkeys need focus to work, does it mean that sometimes pressing `ctrl+s` to save mappings would be missed too if there is no focus?

**Comment by 2xsaiko** [comment]
Just tested, saving works everywhere, including where the search dialog doesn't. As far as I can see, it doesn't use anything different to how the search dialog gets opened, the menu item action listener. Huh???

**Comment by YanisBft** [comment]
After further investigation, the issue comes specifically from using Space bar key in a JTree. According to the docs, space bar selects an entry in a JTree, and registering a key stroke does not override this behavior, unless it is registered directly on the JTree.
So we have two solutions: either changing the default keybind to not use space bar, or registering the key stroke on each JTree.

**Comment by liach** [comment]
I think we should go for a new set of hotkeys. This is also a good opportunity to add hotkeys for searching methods and fields.
