### ISSUE TITLE
Need to patch cfr to handle obfuscated $values methods

### ISSUE THREAD

**Issue by liach** [FabricMC/Enigma#410]
Since this synthetic method is not public, proguard apparently obfuscates it and cfr's detection mechanism, which relies on [exact name match](https://github.com/leibnitz27/cfr/commit/c9268405d6d58d41a604d1f5d202d55309674c5c#diff-b8f79e8b7a2261177f392a9e3d1528d4dddec4ffd0d416da83f9418082e083d9R245), fails.

In addition, the upstream states it won't deal with obfuscation, so having this in our patch would probably be better.

**Comment by YanisBft** [comment]
This is not only methods, the entire enum classes are messed up

**Comment by liach** [comment]
Yeah, that method is the trigger for cfr to beautify enum classes, so we need to patch that line of detection so cfr hides values etc methods generated by javac

**Comment by liach** [comment]
k turns out replacing that `$values` with `null` (any method name) works. I guess it's good enough, as this optimization only runs for enum classes. 
![image](https://user-images.githubusercontent.com/7806504/123548051-d78df300-d728-11eb-9aa7-04f524ac0942.png)
A pr will be sent soon :tm:

**Comment by liach** [comment]
Fixed in latest cfr; you can use gradle to use cfr 0.0.5. #414 will update cfr in enigma to have this fix as well (and also fixes the documentation on enum being in wrong position bug)
