### ISSUE TITLE
Name suggested fields with the suggested names if they have javadoc added

### ISSUE THREAD

**Issue by liach** [FabricMC/Enigma#413]
Partially due to how enigma currently store javadocs, but we can patch this little thing before doing a javadoc storage full restructure.

**Comment by YanisBft** [comment]
This will be unneeded with #364, as javadocs will be tied to an entry no matter its obfuscation

**Comment by YanisBft** [comment]
Can be closed, automapped fields now keep their suggested name after javadocs are added
