### ISSUE TITLE
shadow 7.0.0 breaks publish

### ISSUE THREAD

**Issue by 2xsaiko** [FabricMC/Enigma#415]
The shadow plugin was updated to 7.0.0 in 037a0c3, I just reverted that part because it [crashes gradle when running publish tasks](https://github.com/FabricMC/Enigma/runs/2940616698). Maybe that version needs some more changes to the buildscript to work?

**Comment by Juuxel** [comment]
This should fix it (I had the same issue yesterday in another project):

```diff
        shadow(MavenPublication) { publication ->
-            publication.from components.java
-            publication.artifact shadowJar
+            shadow.component publication
        }
```

(replacing the manual config with a call to the shadow plugin's `ShadowExtension.component(MavenPublication)`)

**Comment by liach** [comment]
@2xsaiko No need to reverse it. In addition to juuxel's note, in fact, even though the task fails, the artifacts are properly published.
