### ISSUE TITLE
enigma doesnt work

### ISSUE THREAD

**Issue by candddddaa** [FabricMC/Enigma#417]
engima doesnt work i cant open it

**Comment by haykam821** [comment]
We need more information than that. How are you launching Enigma?

**Comment by candddddaa** [comment]
clicking it

**Comment by modmuss50** [comment]
What version have you got? What is the file name? I would recommend launching it via yarn but it’s unclear what your intentions are.

**Comment by candddddaa** [comment]
enigma-swing-1.3.3-all file name and version

**Comment by modmuss50** [comment]
Are you using java 16? I would try running it from the console like `java -jar enigma-swing-1.3.3-all.jar` to see what the error is. I imagine its becuase you arent using java 16

**Comment by candddddaa** [comment]
thank u :)
