### ISSUE TITLE
Enigma Swing 1.4.1 crashes when exporting Minecraft 1.17.1 sources

### ISSUE THREAD

**Issue by higgy999** [FabricMC/Enigma#425]
No error log is generated but a separate window as a crash log is opened but white and blank. The original window is still open but stuck on MouseSettingsScreen.java. Is this a memory issue? I have 16 GB and a 16 GB page file. The program pins my CPU at 100%, does Windows kill programs that take the CPU for too long? Should I run CLI instead?

**Comment by liach** [comment]
I think export sources through enigma has been broken for long. Need to check out one day.

**Comment by higgy999** [comment]
> I think export sources through enigma has been broken for long. Need to check out one day.

I have tried exporting only the jar and using another tool to get the actual decompile but It still gives me broken code.

**Comment by liach** [comment]
> still gives me broken code

What decompiler are you using? Notice Minecraft 1.17.1 is on java 16 which a few legacy decompilers don't work well on.

**Comment by higgy999** [comment]
> > still gives me broken code
> 
> What decompiler are you using? Notice Minecraft 1.17.1 is on java 16 which a few legacy decompilers don't work well on.

http://java-decompiler.github.io/
I have specifically java 16 installed aswell

**Comment by higgy999** [comment]
I just ran it on my laptop and went through fine. No idea how or why this worked. Finished in 5 seconds O_o

**Comment by liach** [comment]
Looking at https://github.com/java-decompiler/jd-core, I am almost certain it is largely outdated.

I recommend using https://github.com/leibnitz27/cfr which is the only up-to-date decompiler that I know, though its generated code does have some problems in regards to minecraft still.
