### ISSUE TITLE
Expand name inference to record components

### ISSUE THREAD

**Issue by liach** [FabricMC/Enigma#429]
Dunno if this belongs here or to stitch, but we can examine the `names` argument passed to `ObjectMethods.bootstrap` and the method handle constants to infer names for the record component fields (and potentially methods if they use the default implementation)

**Comment by haykam821** [comment]
Relates to FabricMC/yarn#2681

**Comment by modmuss50** [comment]
This should really be tracked in the yarn issue, the current code for enums is in stitch ( https://github.com/FabricMC/stitch/blob/4289c0e26203c973b2ce96e76eb1c87d9e6388df/src/main/java/net/fabricmc/stitch/util/FieldNameFinder.java) but could do with going somewhere else.

Player suggested using matcher to help with this as it already has a much better understanding of whats going on. Its unclear how this would be made into an engima plugin and possibly seems like a longer term project.

If someone wants something to do, a quick solution in stitch shouldnt be too hard to get working.

**Comment by liach** [comment]
We have https://github.com/FabricMC/name-proposal now, closing.
