### ISSUE TITLE
Bug: Proguard mappings with original source locations cannot be loaded

### ISSUE THREAD

**Issue by Dakror** [FabricMC/Enigma#432]
The Proguard docs define the syntax for a method definition like this:
```
    [startline:endline:]originalreturntype [originalclassname.]originalmethodname(originalargumenttype,...)[:originalstartline[:originalendline]] -> obfuscatedmethodname
```

The current regex for methods looks like this:
```
 {4}(?:[0-9]+:[0-9]+:)?(" + TYPE + ") (" + NAME + ")\\((" + TYPE_LIST + ")\\) -> (" + NAME + ")
```

You can see that the part after the last colon for the original source location is missing.
Mappings that provide these definitions can't be loaded right now, resulting in an "invalid mapping line" error

**Comment by NebelNidas** [comment]
Does [mapping-io](https://github.com/FabricMC/mapping-io/blob/master/src/main/java/net/fabricmc/mappingio/format/ProGuardReader.java) handle this correctly?

**Comment by NebelNidas** [comment]
Should work correctly now that we use Mapping-IO under the hood. If not, feel free to re-open the issue.
