### ISSUE TITLE
> Task :enigma:compileJava FAILED

### ISSUE THREAD

**Issue by rosesxrd** [FabricMC/Enigma#442]
I Need a help
![errorEnigmaGradle](https://user-images.githubusercontent.com/89709625/153758723-74ba9ae3-29bb-47d2-85b3-4b58b0f24238.png)

please help for error

**Comment by modmuss50** [comment]
Enigma requires Java 17 to build.

**Comment by 9alexyt5** [comment]
gradlew build -Dorg.gradle.java.home=/C:\Progra~1\Java\jdk-17.0.3.1
