### ISSUE TITLE
Reset obf seems unefective

### ISSUE THREAD

**Issue by darkhax** [FabricMC/Enigma#47]
I accidently named a parameter in a sub class. Using reset to obf had seemingly no effect from the sub class. By going to the main class and resetting it there, it did work, however all sub classes still have the new mapping.

**Comment by asiekierka** [comment]
Argument names cannot be reset-to-obf as the propagation is not mandatory there, unlike method names.

**Comment by Thog** [comment]
I can fix it to remove the value in the mother class. The actual issue is that it doesn't propagate it to children classes in some case because the mapping is duplicate.

**Comment by gegy1000** [comment]
Believe this is resolved now
