### ISSUE TITLE
Default param names are sometimes mixed up

### ISSUE THREAD

**Issue by maxpowa** [FabricMC/Enigma#49]
![bug](https://u.xpw.us/hg9gel.png)

The `PotionEffectType` is named `aInteger4` and the `int` is named `aPotionEffectType5`. This is in an inner class, haven't seen elsewhere.

**Comment by asiekierka** [comment]
It does only happen on inner classes. They're a bit special.

2016-10-18 19:08 GMT+02:00 Max Gurela <notifications@github.com>:
