### ISSUE TITLE
Exporting source does nothing

### ISSUE THREAD

**Issue by skyrocketc** [FabricMC/Enigma#526]
When i try to export the deobfuscated source, it does nothing.

**Comment by Guigui220D** [comment]
#494

**Comment by Enaium** [comment]
[enigma-swing-2.3.3-all-fix-export-source.zip](https://github.com/FabricMC/Enigma/files/14041936/enigma-swing-2.3.3-all-fix-export-source.zip)

**Comment by NebelNidas** [comment]
Duplicate of #487.
