### ISSUE TITLE
Crash when opening jar

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/Enigma#534]
Steps to reproduce (on my machine at least):
1. Open Enigma (enigma-swing-2.3.3-all.jar) with Java 21 (does not happen with Java 17)
2. Press File > Open JAR and navigate to a specific directory (happens in Windows' downloads directory for me)

Log: https://gist.github.com/Juuxel/4f8e16ef6e607d030112d3d10423d151

**Comment by PiTheGuy** [comment]
This is fixed in a newer version.
