### ISSUE TITLE
Incorrect unmapped parameters

### ISSUE THREAD

**Issue by darkhax** [FabricMC/Enigma#58]
Looking at Item$ToolMaterial, the unmapped constructor arguments are not correct. For example, `final int aString1`. At first I thought this was just a display issue, but it seems that saving the mappings will also fail to save any of the mappings for the arguments. 

![image](https://cloud.githubusercontent.com/assets/2250798/26007619/9432ffac-36fe-11e7-9cfd-6b5db7c544d5.png)

**Comment by asiekierka** [comment]
As far as I know, this is a known issue for inner constructors. Should be fixed anyway.

**Comment by Thog** [comment]
@asiekierka Nan it's related to the Enum structure
