### ISSUE TITLE
Cannot rename field

### ISSUE THREAD

**Issue by Prospector** [FabricMC/Enigma#69]
https://streamable.com/37u0p

**Comment by quat1024** [comment]
Related? https://streamable.com/shv9b

**Comment by liach** [comment]
I think so.

**Comment by quat1024** [comment]
important is that pros's remained red, while mine turned green when I tried to rename it!

**Comment by asiekierka** [comment]
LVTs are a bit more strange than Prospector's issue, so those two should be separate.

**Comment by asiekierka** [comment]
@ProfessorProspector 's issue should be fixed as of the latest "0.12.2" build.

**Comment by YanisBft** [comment]
Closing this as no objections were made to asie comment since more than 2 years
