### ISSUE TITLE
New issue with tokens being mapped to the wrong objects or something

### ISSUE THREAD

**Issue by Prospector** [FabricMC/Enigma#72]
I had not noticed this issue before asie's recent change adding the enums and stuff (and I was mapping this exact same class before and it was not happening--class `cfe`) 
![image](https://user-images.githubusercontent.com/6166773/49693209-54343400-fb21-11e8-8551-8730473cb27a.png)

**Comment by asiekierka** [comment]
Did build .56 fix it?

**Comment by YanisBft** [comment]
No longer an issue
