### ISSUE TITLE
Can't modify abstract method arguments in some cases

### ISSUE THREAD

**Issue by Barteks2x** [FabricMC/Enigma#78]
Example: most of the abstract methods in 18w50a class `cep` (`class_3554`). Renaming them highlights them as green, but doesn't actually show changed name

**Comment by shadowfacts** [comment]
Are the mappings saved and the UI not updated or are the mappings not being saved either?

**Comment by gegy1000** [comment]
There is an off-by-one offset with the argument indices. Likely related to #66, either caused this issue, or needs to be applied to this issue.
