### ISSUE TITLE
Quick Find dialog too low

### ISSUE THREAD

**Issue by MasterEric** [FabricMC/Enigma#84]
![screenshot 108](https://user-images.githubusercontent.com/4635334/50035537-99001500-ffd0-11e8-942d-5a48b6e5b18b.png)

It extends to outside the window. If the window is maximized, it will extend to underneath the taskbar, making it impossible to read.

**Comment by liach** [comment]
For now, you can choose not to make enigma fullscreen to see the search bar.

**Comment by liach** [comment]
Another issue with search: the loop around option only works when you click the down arrow. It is not working with the up arrow

**Comment by Thog** [comment]
If I remember correctly, the quick search bar wasn't there before, it got activated because I made a mistake back then so it's normal that it's still buggy.

**Comment by gegy1000** [comment]
Closed in https://github.com/FabricMC/Enigma/commit/06efc97fa238cadf70c04a494b166d69358e9b0e
