### ISSUE TITLE
Always pull method names from the most parent classes; do not store them in child class mappings

### ISSUE THREAD

**Issue by asiekierka** [FabricMC/Enigma#97]
@gegy1000 Mind looking into it later?

**Comment by gegy1000** [comment]
I think this would be worth addressing in #91; currently has some issues with mappings from parent classes. Will definitely look into it.

**Comment by gegy1000** [comment]
Should the mappings files still contain mappings from children?

**Comment by asiekierka** [comment]
No point. They're stripped by the Enigma->Tiny converter regardless.

**Comment by liach** [comment]
How about a method with the same name shared by two interfaces, none of which is the ancestor of another?
E.g.
a
| \
b c
| /
d
if interface b and c both adds method "z", where should the method mapping go?

**Comment by asiekierka** [comment]
To both interface "b" and "c" as it stands, as they do not have a common parent.

**Comment by gegy1000** [comment]
Good point, will have to test that this works!

**Comment by asiekierka** [comment]
Well, that's merged
